language: node_js
node_js:
   - 8

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod
before_deploy: "git push origin master:refs/heads/master"
deploy:
   provider: azure_web_apps
