language: node_js
node_js:
   - 8
cache:
  directories:
    - node_modules

branches:
   only:
      - master

notifications:
  email: false
  slack:
    rooms:
      - cs2016a:MrE8tgSmsfcVCMVTa1JgT78G
    on_success: change
    on_failure: always
    template:
      - "%{author} %{result} build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) in %{repository}@%{branch}"
      - "Travis message: %{message}"
      - "Commit message: %{commit_message}"

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod

after_script:
  - cd dist
  - git init
  - git add .
  - git commit -m "New Release"
  - git remote add azure $repo
  - git push azure master --force
